
import React from 'react';
import { 
  Home, 
  MessageSquare, 
  Info, 
  BookOpen, 
  CheckSquare, 
  Target,
  Plus,
  Trash2,
  CheckCircle2,
  Circle,
  X,
  Settings,
  Calendar as CalendarIcon,
  RefreshCw,
  Moon,
  Sun,
  Globe,
  Bell
} from 'lucide-react';

export const ICONS = {
  Menu: Home,
  Assistant: MessageSquare,
  About: Info,
  Books: BookOpen,
  TodoList: CheckSquare,
  Goals: Target,
  Plus: Plus,
  Trash: Trash2,
  Check: CheckCircle2,
  Uncheck: Circle,
  Close: X,
  Settings: Settings,
  Calendar: CalendarIcon,
  Routine: RefreshCw,
  Moon: Moon,
  Sun: Sun,
  Globe: Globe,
  Bell: Bell
};

export const MOTIVATIONAL_QUOTES = {
  fa: [
    { text: "تنها راه انجام کارهای بزرگ، عاشق بودن به کاری است که انجام می‌دهید.", author: "استیو جابز" },
    { text: "باور داشته باش که می‌توانی، نیمی از راه را رفته‌ای.", author: "تئودور روزولت" },
    { text: "راز پیشی گرفتن در شروع کردن است.", author: "مارک تواین" },
    { text: "موفقیت یعنی رفتن از شکستی به شکست دیگر بدون از دست دادن اشتیاق.", author: "وینستون چرچیل" },
    { text: "بزرگترین ریسک، ریسک نکردن است.", author: "مارک زاکربرگ" },
    { text: "آینده متعلق به کسانی است که به زیبایی رویاهایشان باور دارند.", author: "النور روزولت" },
    { text: "انضباط، پل بین اهداف و دستاوردهاست.", author: "جیم ران" },
    { text: "سخت‌کوشی هیچ جایگزینی ندارد.", author: "توماس ادیسون" },
    { text: "یا راهی خواهم یافت، یا راهی خواهم ساخت.", author: "هانیبال" },
    { text: "هر روز یک فرصت تازه برای بهتر شدن است.", author: "ناشناس" },
    { text: "تمرکز، کلید باز کردن پتانسیل‌های پنهان است.", author: "ناشناس" },
    { text: "شکست، فرصتی است برای شروع دوباره، این بار هوشمندانه‌تر.", author: "هنری فورد" },
    { text: "محدودیت‌های شما فقط در ذهن شما هستند.", author: "ناشناس" },
    { text: "کاری را انجام دهید که می‌ترسید، و ترس خواهد مرد.", author: "رالف والدو امرسون" },
    { text: "رویاهای خود را دنبال کنید، آن‌ها راه را بلدند.", author: "ناشناس" },
    { text: "تغییرات بزرگ از قدم‌های کوچک شروع می‌شوند.", author: "لائوتسه" },
    { text: "بهترین انتقام، یک موفقیت عظیم است.", author: "فرانک سیناترا" },
    { text: "زندگی کوتاه‌تر از آن است که معمولی بمانید.", author: "ناشناس" },
    { text: "هر قهرمانی زمانی یک مبتدی بوده که تسلیم نشده است.", author: "ناشناس" },
    { text: "صبر تلخ است، اما میوه‌اش شیرین.", author: "سعدی" }
  ],
  en: [
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
    { text: "There is no substitute for hard work.", author: "Thomas Edison" },
    { text: "I will either find a way, or make one.", author: "Hannibal" },
    { text: "Every day is a second chance.", author: "Anonymous" },
    { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
    { text: "Failure is the opportunity to begin again more intelligently.", author: "Henry Ford" },
    { text: "Your only limit is your mind.", author: "Anonymous" },
    { text: "Do what you fear and the death of fear is certain.", author: "Ralph Waldo Emerson" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "Life is too short to be average.", author: "Anonymous" },
    { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" }
  ]
};

export const TRANSLATIONS = {
  fa: {
    menu: "منو",
    assistant: "دستیار",
    calendar: "تقویم",
    about: "درباره",
    settings: "تنظیمات",
    books: "کتاب‌ها",
    tasks: "لیست کارها",
    goals: "اهداف من",
    routine: "روتین شخصی",
    dailyWisdom: "خرد روزانه",
    reading: "در حال خواندن",
    pending: "باقی‌مانده",
    reached: "محقق شده",
    add: "افزودن",
    delete: "حذف",
    theme: "تم برنامه",
    language: "زبان",
    notifications: "اعلان‌ها",
    light: "روشن",
    dark: "تاریک",
    reachedText: "بالآخره بهش رسیدم!",
    tryingText: "در حال تلاش برای رسیدن",
    noData: "هنوز موردی اضافه نشده است.",
    routineSubtitle: "کارهای تکرارشونده روزانه",
    dreamBig: "رویاهای بزرگ داشته باش",
    nextMilestone: "هدف بعدی تو چیه؟",
    shortTerm: "کوتاه مدت",
    longTerm: "بلند مدت",
    setGoal: "ثبت هدف جدید",
    noGoals: "هنوز هدفی نداری. آینده‌ت رو از اینجا بساز!",
    eventsTitle: "مناسبت‌های امروز",
    noEvents: "مناسبت خاصی برای این تاریخ ثبت نشده است."
  },
  en: {
    menu: "Menu",
    assistant: "Assistant",
    calendar: "Calendar",
    about: "About",
    settings: "Settings",
    books: "Books",
    tasks: "Tasks",
    goals: "Goals",
    routine: "Personal Routine",
    dailyWisdom: "Daily Wisdom",
    reading: "Reading",
    pending: "Pending",
    reached: "Reached",
    add: "Add",
    delete: "Delete",
    theme: "Theme",
    language: "Language",
    notifications: "Notifications",
    light: "Light",
    dark: "Dark",
    reachedText: "I finally reached it!",
    tryingText: "Working towards it",
    noData: "Nothing added yet.",
    routineSubtitle: "Daily repetitive tasks",
    dreamBig: "Dream Big",
    nextMilestone: "What's your next milestone?",
    shortTerm: "Short Term",
    longTerm: "Long Term",
    setGoal: "Set Goal",
    noGoals: "No goals yet. Define your future!",
    eventsTitle: "Today's Events",
    noEvents: "No special events for this date."
  }
};
